apiVersion: apps/v1
kind: Deployment
metadata:
  name: download-deployment
  namespace: microservices
spec:
  replicas: 1
  selector:
    matchLabels:
      app: download-service
  template:
    metadata:
      labels:
        app: download-service
    spec:
      containers:
      - name: download-service-container
        image: download-service:latest
        imagePullPolicy: IfNotPresent
        ports:
        - name: grpc
          containerPort: 50052
        - name: http
          containerPort: 5002
        env: # Injeta as URLs dos serviços internos como variáveis de ambiente
        - name: PROTOCOL
          value: "grpc"