apiVersion: apps/v1
kind: Deployment
metadata:
  name: download-deployment
  namespace: microservices-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: download-service
  template:
    metadata:
      labels:
        app: download-service
    spec:
      containers:
      - name: download-service-container
        image: download-service:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5002