apiVersion: v1
kind: Service
metadata:
  name: download-service
  namespace: microservices-app
spec:
  selector:
    app: download-service
  ports:
    - protocol: TCP
      port: 5002
      targetPort: 5002
  type: ClusterIP