apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway-deployment
  namespace: microservices
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gateway-service
  template:
    metadata:
      labels:
        app: gateway-service
    spec:
      containers:
      - name: gateway-service-container
        image: gateway-service:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 3000
        env: # Injeta as URLs dos serviços internos como variáveis de ambiente
        - name: PLAYLISTS_GRPC_URL
          value: "grpc-playlist-service:50051" # K8s DNS: <service-name>:<port>
        - name: DOWNLOADS_GRPC_URL
          value: "grpc-download-service:50052"
        - name: PORT
          value: "3000"
        - name: PROTO_DIR
          value: ./proto
        - name: NODE_ENV
          value: development