apiVersion: apps/v1
kind: Deployment
metadata:
  name: ngrok-deployment
  namespace: microservices-app
  labels:
    app: ngrok
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ngrok
  template:
    metadata:
      labels:
        app: ngrok
    spec:
      containers:
      - name: ngrok
        image: ngrok/ngrok:latest
        ports:
        - containerPort: 4040
        env:
        - name: NGROK_AUTHTOKEN
          valueFrom:
            secretKeyRef:
              name: ngrok-authtoken
              key: AUTHTOKEN
        args:
        - "http"
        - "ingress-nginx-controller.ingress-nginx:80"
        - "--host-header=meu-gateway.exemplo.com"
        - "--log=stdout"