apiVersion: v1
kind: Service
metadata:
  name: playlist-service
  namespace: microservices-app
spec:
  selector:
    app: playlist-service
  ports:
    - protocol: TCP
      port: 5001
      targetPort: 5001
  type: ClusterIP