apiVersion: apps/v1
kind: Deployment
metadata:
  name: playlist-deployment
  namespace: microservices-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: playlist-service
  template:
    metadata:
      labels:
        app: playlist-service
    spec:
      containers:
      - name: playlist-service-container
        image: playlist-service:latest
        imagePullPolicy: IfNotPresent
        ports:
        - name: grpc
          containerPort: 50051
        - name: http
          containerPort: 5001