apiVersion: apps/v1
kind: Deployment
metadata:
  name: grpc-download-deployment
  namespace: microservices
spec:
  replicas: 3
  selector:
    matchLabels:
      app: grpc-download-service
  template:
    metadata:
      labels:
        app: grpc-download-service
    spec:
      containers:
      - name: grpc-download-service-container
        image: grpc-download-service:latest
        imagePullPolicy: Never
        ports:
        - name: grpc
          containerPort: 50052
        resources:
          requests:
            cpu: "200m"  # Requisita 0.2 CPU core (200 millicores)
            memory: "128Mi"
          limits:
            cpu: "500m"  # Limita a 0.5 CPU core
            memory: "256Mi"