apiVersion: v1
kind: Service
metadata:
  name: grpc-download-service
  namespace: microservices
spec:
  selector:
    app: grpc-download-service
  type: ClusterIP
  ports:
    - name: grpc
      protocol: TCP
      port: 50052
      targetPort: 50052
    - name: metrics
      protocol: TCP
      port: 9464
      targetPort: 9464