apiVersion: apps/v1
kind: Deployment
metadata:
  name: grpc-playlist-deployment
  namespace: microservices
spec:
  replicas: 3
  selector:
    matchLabels:
      app: grpc-playlist-service
  template:
    metadata:
      labels:
        app: grpc-playlist-service
    spec:
      containers:
      - name: grpc-playlist-service-container
        image: kadesh67/grpc-playlist-service:latest
        imagePullPolicy: Always
        ports:
        - name: grpc
          containerPort: 50051
        env:
        - name: DOWNLOADS_GRPC_URL
          value: "grpc-download-service:50052"
        resources:
          requests:
            cpu: "200m"  # Requisita 0.2 CPU core (200 millicores)
            memory: "128Mi"
          limits:
            cpu: "500m"  # Limita a 0.5 CPU core
            memory: "256Mi"