apiVersion: v1
kind: Service
metadata:
  name: rest-download-service
  namespace: microservices
spec:
  selector:
    app: rest-download-service
  type: ClusterIP
  ports:
    - name: http
      protocol: TCP
      port: 5002
      targetPort: 5002