apiVersion: v1
kind: Service
metadata:
  name: rest-download-service
  namespace: microservices
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/path: "/metrics"
    prometheus.io/port: "5002"
spec:
  selector:
    app: rest-download-service
  type: ClusterIP
  ports:
    - name: http
      protocol: TCP
      port: 5002
      targetPort: 5002