apiVersion: v1
kind: Service
metadata:
  name: rest-playlist-service
  namespace: microservices
  labels:
    app: rest-playlist-service
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/path: "/metrics"
    prometheus.io/port: "5001"
spec:
  selector:
    app: rest-playlist-service
  type: ClusterIP
  ports:
    - name: http
      protocol: TCP
      port: 5001
      targetPort: 5001