apiVersion: apps/v1
kind: Deployment
metadata:
  name: rest-download-deployment
  namespace: microservices
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rest-download-service
  template:
    metadata:
      labels:
        app: rest-download-service
    spec:
      containers:
      - name: rest-download-service-container
        image: rest-download-service:latest
        imagePullPolicy: IfNotPresent
        ports:
        - name: http
          containerPort: 5002